###Add
POST http://localhost:8080/api/orders
Content-Type: application/json

{
  "customerName": "Vali",
  "customerEmail": "Vali@mail.ru"
}
###List
GET http://localhost:8080/api/orders

###Get
GET http://localhost:8080/api/orders/2

###Delete
DELETE http://localhost:8080/api/orders/8

###changeStatusById

PUT http://localhost:8080/api/orders/1/CANCELLED

###getAllByEmail
GET http://localhost:8080/api/orders/customer/Valiyevmail