### add
POST http://localhost:8080/api/profile/registration
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "fullName": "Moxirbek",
  "email": "erkinov@email.uz",
  "password": "123"
}
### get
GET http://localhost:8080/api/profile/erkinov@email.uz
Authorization: Bearer {{jwt}}

### getAll
GET http://localhost:8080/api/profile
Authorization: Bearer {{jwt}}

###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "",
  "password": ""
}
