###Add
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "name": "Non",
  "price": 5000,
  "stock": "12",
  "category": "Hamir"
}
###List
GET http://localhost:8080/api/products

###Get
GET http://localhost:8080/api/products/3

###updateById

PUT http://localhost:8080/api/products/1
Content-Type: application/json

{
  "name": "Pepsi",
  "price": 12000,
  "stock": "12",
  "category": "Gazli SUV"
}


###Delete
DELETE http://localhost:8080/api/products/5